version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "daily"
      time: "09:10"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"
