import { defineConfig } from "@pandacss/dev";

const cssVar = (name: string) => ({ value: `var(--${name})` });

export default defineConfig({
  preflight: true,
  strictTokens: true,
  strictPropertyValues: true,
  syntax: "object-literal",
  include: [
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
    "./.storybook/**/*.{ts,tsx}",
  ],
  exclude: [],
  outdir: "styled-system",
  theme: {
    extend: {
      tokens: {
        colors: {
          black: { value: "#000000" },
          white: { value: "#ffffff" },
          notFoundOverlay: { value: "rgba(0, 0, 0, 0.45)" },
          whiteAlpha60: { value: "rgba(255, 255, 255, 0.6)" },
          whiteAlpha80: { value: "rgba(255, 255, 255, 0.8)" },
          whiteAlpha90: { value: "rgba(255, 255, 255, 0.9)" },
          postHoverTitle: { value: "#0a3d4e" },
          postHoverMeta: { value: "rgba(26, 26, 26, 0.7)" },
          postHoverBody: { value: "rgba(26, 26, 26, 0.75)" },
          postHoverBorder: { value: "rgba(26, 26, 26, 0.3)" },
        },
        fontSizes: {
          "2xs": { value: "0.6875rem" },
          "account-xs": { value: "0.75rem" },
          "account-sm": { value: "0.8125rem" },
          "account-md": { value: "0.875rem" },
          "account-lg": { value: "0.9375rem" },
          "icon-md": { value: "1.125rem" },
          "icon-lg": { value: "1.375rem" },
          "rotator": { value: "1.25rem" },
        },
        sizes: {
          dvh: { value: "100dvh" },
          "icon-sm": { value: "1.25rem" },
          "icon-md": { value: "1.5rem" },
          "control": { value: "2.5rem" },
          "language-control": { value: "5rem" },
          "control-orb": { value: "6rem" },
          "control-knob": { value: "2rem" },
          "timeline-dot": { value: "0.75rem" },
          "account-platform": { value: "6rem" },
          "account-platform-md": { value: "7rem" },
          "account-copy": { value: "2.5rem" },
          "content-3xl": { value: "48rem" },
          "content-4xl": { value: "56rem" },
          "card-sm": { value: "17.5rem" },
        },
        spacing: {
          half: { value: "50%" },
          "timeline-dot-offset": { value: "-0.375rem" },
          "history-y": { value: "5rem" },
          "page-y": { value: "6rem" },
          "control-offset": { value: "1.5rem" },
          "not-found-bg": { value: "110vmax" },
          "account-row-hover": { value: "1.25rem" },
        },
        radii: {
          control: { value: "9999px" },
          item: { value: "0.625rem" },
          tag: { value: "0.6875rem" },
        },
        durations: {
          fast: { value: "100ms" },
          interaction: { value: "200ms" },
          medium: { value: "250ms" },
          slow: { value: "300ms" },
          slower: { value: "400ms" },
          toggle: { value: "500ms" },
        },
        easings: {
          easeOut: { value: "ease-out" },
          easeInOut: { value: "ease-in-out" },
        },
        lineHeights: {
          none: { value: "1" },
          tight: { value: "1.2" },
          snug: { value: "1.375" },
          relaxed: { value: "1.625" },
          section: { value: "1.75rem" },
        },
        letterSpacings: {
          label: { value: "0.08em" },
          wideLabel: { value: "0.3em" },
          notFound: { value: "0.35em" },
          tight: { value: "-0.025em" },
        },
        shadows: {
          md: { value: "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)" },
          sm: { value: "0 1px 2px 0 rgb(0 0 0 / 0.05)" },
          accountText: { value: "0 1px 4px rgba(0, 0, 0, 0.2)" },
          orbitPill: cssVar("orbit-pill-shadow"),
        },
        zIndex: {
          base: { value: "0" },
          canvas: { value: "1" },
          content: { value: "10" },
          overlay: { value: "15" },
          controls: { value: "20" },
          header: { value: "40" },
        },
      },
      semanticTokens: {
        colors: {
          background: cssVar("background"),
          foreground: cssVar("foreground"),
          theme: {
            accent: cssVar("theme-accent"),
          },
          accent: {
            dynamic: cssVar("accent"),
          },
          text: {
            primary: cssVar("text-primary"),
            secondary: cssVar("text-secondary"),
            tertiary: cssVar("text-tertiary"),
          },
          border: {
            subtle: cssVar("border-subtle"),
            subtleStrong: cssVar("border-subtle-strong"),
          },
          control: {
            bg: cssVar("control-bg"),
            fg: cssVar("control-fg"),
            fgStrong: cssVar("control-fg-strong"),
            border: cssVar("control-border"),
            orb: cssVar("control-orb"),
            labelActive: cssVar("control-label-active"),
            labelMuted: cssVar("control-label-muted"),
            knob: cssVar("control-knob"),
            knobInner: cssVar("control-knob-inner"),
          },
          timeline: {
            line: cssVar("timeline-line"),
            dotBg: cssVar("timeline-dot-bg"),
            dotBorder: cssVar("timeline-dot-border"),
            date: cssVar("timeline-date"),
            title: cssVar("timeline-title"),
            description: cssVar("timeline-description"),
          },
          orbit: {
            pillBg: cssVar("orbit-pill-bg"),
            pillBorder: cssVar("orbit-pill-border"),
            pillBorderStrong: cssVar("orbit-pill-border-strong"),
            pillText: cssVar("orbit-pill-text"),
            pillTextStrong: cssVar("orbit-pill-text-strong"),
            pillShadow: cssVar("orbit-pill-shadow"),
          },
          blog: {
            body: cssVar("blog-body"),
            heading: cssVar("blog-heading"),
            link: cssVar("blog-link"),
            linkHover: cssVar("blog-link-hover"),
            chipBorder: cssVar("blog-chip-border"),
            chipBg: cssVar("blog-chip-bg"),
            chipText: cssVar("blog-chip-text"),
            previewBorder: cssVar("blog-preview-border"),
            previewBg: cssVar("blog-preview-bg"),
            previewBgHover: cssVar("blog-preview-bg-hover"),
            previewTitle: cssVar("blog-preview-title"),
            previewDesc: cssVar("blog-preview-desc"),
            previewUrl: cssVar("blog-preview-url"),
          },
        },
      },
    },
  },
});
