#+TITLE: 2026 年度上半期振り返り
#+DESCRIPTION: 4 月 - 9 月まとめ
#+TAGS: 振り返り インターン
#+DATE: 2026-10-01
#+DRAFT: false

* はじめに
2026 年 4 月から 9 月について振り返っていこうと思う。

* やったこと
** 一人暮らしの地盤固め
筑波大学に進学するにあたって、当然実家 (大阪) を出る必要がある。

*** 回線
光回線として NURO 光を頼んだんだが、引く実績がなくて時間がかかるからフレッツ光にした方がいいですよと言われたのでしばらく引けなかった。意外と無料インターネットも早くて VRChat できるっちゃできたので、引かなくても良かったかもしれない。まあ引いたけど。

モバイル回線は povo に変えた。MNP しようにも親の名義で回線を契約していたので、どうにか親のいる間に回線の名義変更を行っている。

*** 家具
ほとんど親の金で買った。

多動症なので、昇降デスクを買ってから 30 分に 1 回立っている。
[@preview](https://www.amazon.co.jp/dp/B0F7Q9NSP1)

しばらく椅子がなかったのでずっと立っていたが、1 週間くらい経ってまあ安いの買えばいいかと思って買った。リクライニングがないのであんまりよくない。
[@preview](https://www.amazon.co.jp/dp/B0BN1NVL59)

今は 1 万円台で 144 hz のモニターが買えていい時代だ。
[@preview](https://www.amazon.co.jp/dp/B0GCC92XD8)

*** スマートホーム
Sesame と Switch Bot で迷ったが、安いので Sesame にした。

[@preview](https://jp.candyhouse.co/products/sesame5)

家の鍵とエアコンと照明を外からいじれるように今のところなっており、夏は帰り際につけるとキンキンになっていいね。

** インターン
引っ越し後のオリエンテーション期間だが、オリエンテーションを十分に楽しむ間もなくインターン（と途中で面倒になってやめた奨学金）の申し込みを行っていた。

将来のためとはいえ、これに上半期のほとんどを破壊されているので就活の早期化は喜ばしくないわね。

そんなに応募した記憶はないんだが、ただ書類だけ出してそれ以降やる気がなくなった企業を含めたら 17 社に応募していた（含めなければ 9 社だった）。そのうち 5 社に合格して日程の都合上 4 社のインターンに参加した。

- Sansan
  - 5/22 合格
  - 7 月中にインターンに参加
- freee
  - 6/12 合格
  - 6/19 辞退 (はてなとの日程重複のため)
- Progate
  - 6/15 合格
  - 8 月中にインターンに参加
- pixiv
  - 6/17 合格
  - 9 月中にインターンに参加
- Hatena
  - 6/19 合格
  - 8, 9 月中にインターンに参加

こう見ると最速で動いても 6 月中旬に結果が出ることがほとんどであることがわかる。

ずっと Pending のタスクが生える感じで、心理的に安全ではない。結果が良かっただけまだいいが、全落ちしてたら目も当てられない。就活早期化はマジで是正して欲しい......

インターン参加については記事にする/したのでここでは語らないこととします

** 授業への参加
LLM のおかげで学生がやることって出席だけになってしまった。つか出席すらしてないかも。3 回はサボれるから
TWINS と manaba と respon を CLI にしたので、なんかよしなにやるといいらしい:

[@preview](https://github.com/Kyure-A/twins-cli)
[@preview](https://github.com/Kyure-A/manaba-cli)
[@preview](https://github.com/Kyure-A/respon-cli)

** 帰省
8 月半ばから 9 月いっぱい大阪の実家にいたが、大阪がいい場所であるだけで実家は制限があって不便だということに気づいた。
今後はこんな長期間帰らない気がします。

* やっていないこと
** サークルへの参加
インターンの面接が平日の夕方らへんとかに入りまくっているので、参加が不可能！
馴染めないため、必然的に編入生の友人とつるんでいました。まあいいと思う。

** 自炊
- シンクが狭すぎて洗い物をするのが億劫になる → 料理しても溜まるので皿がなくなる → Uber Eats に頼る
- 炊飯器が壊れて米が炊けなくなる → 鍋で炊くのは面倒臭い → Uber Eats に頼る

など、Uber Eats ばっかりしていたら太ってしまった。Uber Eats の料理って基本的には "ハレ" と "ケ" のうち "ハレ" の料理しかないので、当然太る。

洗い物への対策としては

- 皿にラップをかけて食う
- 都度洗う
- 紙皿を使う

などあるだろうが、後者 2 つは実践できていなかったのでラップはやってみようかなと思っている。

米については炊飯器を買えば解決する話なので、買いました

あと nosh を契約したので洗い物も減るかもしれない

** 掃除
ゴミ箱が 1 箇所かつ小さいせいで床に投げがちになっていた。少なくとも 2 箇所にゴミ箱を用意した上で、より大きいものを使ったほうがよいだろうな。

** 節制
自炊で解決できるのだが、Uber Eats のしすぎというのが一番にありそうだ。

あとは LLM かもしれない。正直 3 万円かけてやっていることがマネタイズできていない。

小口で物を買いすぎだなと思う。1 日 3000 円使うだけで 9 万円になるわけですからね。足りるわけがない
これを解決したくて、浪費用プリペイドカード / デビットカードを作るとかしたほうがいいかもねになった。

高専の頃はクレジットカードを運用していなかったので、残高を切り詰めて生活するなど緊迫感があったため。
とりあえず Revolut を開設した。割と海外決済しなくもない都合上ちょうど良さそう。

親から仕送りとして 10 万円/月 送られてきているのが本当に浪費に拍車をかけている。

* まとめ
- 一人暮らしいけてるけど金使いすぎだし家散らかりすぎだ
- インターンの調子いいからまあヌルッと就職できそう！
- 実家は居心地いいようで微妙
