#+TITLE: 筑波大学 2026 年度 春学期 授業感想
#+DATE: 2026-07-01
#+DESCRIPTION: 2026 年度春学期に筑波大学 (主に春日エリア) で開講された授業の感想をまとめた
#+TAGS: 筑波大学
#+DRAFT: true

** はじめに
キュレェです。筑波大学に編入して春学期が終わった。主観に基づいて授業を逆評価していこうと思うぜ。
俺は klis に編入したわけだが、1, 2 年次が標準履修年度にもかかわらず単位認定されないせいで 3 年次に取らされる科目が結構あるので、編入でない klis の 3 年生と比べるとかなり異質な履修になっていると思います。

一応、認定単位としては 67 単位スタートなので 4 年次に進級するには残り 33 単位取得すればよい計算です。

** 授業
先に履修するのをやめた授業を紹介して、その次に受け切った授業を紹介する形式でいきます。
一応 3 年春学期の履修の方針としては:

- 火曜はオンデマンドの日
- 金曜は全休

でした。このおかげで木曜日を超えると 3 連休が来るのですが、友人には「華木」と揶揄されていました。

*** 切った授業
**** GE62001 / 生命情報学
- 春 AB / 木 5,6 / 2 単位 / 3・4 年次
- 対面

遺伝情報とか脳の持つ情報が......みたいな話をやるらしいのだが、初回の授業で手書きのレポートを要求されたり「疑問」と「質問」は違いますよみたいな話をくどくどされたりした。要は明らかに教員の求める学習時間とコストが見合わないので切ったのである。

教員自体の雑談も変で、ドナルド・トランプや政治の批判ばかりしていた。1 回目の授業にもかかわらず初回 10 分で数人が退室していくなど、かなり壮観。友人も退室しており、俺もつられて 1 回目で切ったので実際どうなのかはわかりません。

**** GE60201 / テクニカルコミュニケーション
- 春 AB / 火 5,6 / 2 単位 / 3・4 年次
- オンライン (オンデマンド, 同時双方向併用)

よくわからないけど Twitter を使って授業をやっていて面白そうだった。友人がやっていて実際面白いんだと思うが、俺は同時双方向併用の週があるのがちょっと嫌で切ってしまった。火曜日をオンデマンド授業の日にしているので......

**** GC52801 / 情報デザインII
- 春 AB / 火 3 / 1 単位 / 3・4 年次
- 対面

[[https://いなにわうどん.みんな/class-impression/2023spring][いなにわうどんさんのレビュー]]を見てから受ければよかったなと後悔している授業。教室移動的には問題なかった気もするが、なぜか切ってしまった。一瞬履修したけどすぐ外したので一度も受けていません（それは切ったと言えるのだろうか）
楽しそうとはいえ相応の負担がありそうだから受けるにしても 4 年で良かった感も今はある。

*** 受けた授業
**** 1227641 / 学問への誘い / P
- 春 A / 水 5, 6 / 1 単位 / 1 年次
- オンデマンド
- 総合科目

なにこれ？

**** GA14111 / 知識情報概論 / A+
- 春 A / 火 1,2 / 1 単位 / 1 年次
- オンデマンド
- 専門基礎科目 (必修)

コロナ禍に開発されたにしては超高性能なマルチモーダル AI が宇陀先生とイチャイチャしながら「知識共有現象」という言葉を覚えさせてくる授業。
火曜に授業があるくせに最後のテストが月曜の 1 限の時間にオンデマンドで行われるカス仕様。その日は高専の友人が泊まりにきており、ひたすらつくばを散歩した末に酒飲んで寝落ちしていたので、目覚ましをかけていて起きられたのが奇跡だった。
酔ってても 100 点取れました。

**** GE11022 / 知識情報演習I-2 / B
- 春 AB / 水 1,2 / 2 単位 / 2 年次
- 専門基礎科目 (必修)

半期ごとのオムニバス形式で開講される授業。1, 2 限に必修を入れないで欲しい。

春 A は図書館目録についての授業だったのだが、覚えている単語は「ダブリンコア」とかいうクソかっこいい単語のみだ。他は何も覚えていない......

春 B は ipnyb で OPAC を作る授業だった。何も覚えていない......

**** GE11122 / 知識情報演習II-2 / 履修中
- 春 C 秋 A / 水 1,2 / 2 単位 / 2 年次
- 専門基礎科目 (必修)

半期ごとのオムニバス形式で開講される授業......、え？春 C もやるんですか？秋 A にまたがる？？どういうこと？？？

春 C はインターンを入れたのでほとんど欠席するつもりだったんですが、対面かつレポートもその場で手書き提出とかいう 2026 年とは思えないアナログさで逆に清々しいです。
秋学期の感想でもこの授業が出てくると思います（TWINS の学期区分的には一応秋学期の授業）

**** GE21401 / メディア社会学 / 履修中
あんまわかりません

**** GE70113 / 知識情報システム実習A / A
- 春 AB / 月 5,6 / 1 単位 / 3 年次
- 対面
- 専門科目 (必修)

アプリ開発しようね！みたいな実習。主専攻実習が月曜にあるのは珍しいらしく、他の情報学群の学生によく驚かれる。
全員 Vibe Coding してアプリケーションを作っており、これって身になっているのか？と思った。俺は授業中に OSS 作ったりしてました。

**** GE50722 / 専門英語 B-2 / A
- 春 AB / 月 4 / 1 単位 / 3 年次
- 対面
- 専門科目 (必修)

文章を読んでからテーマに沿ってアカデミックライティングをしよう！みたいな授業である。授業中は kahoot というツールでインタラクティブだ。名前でボケる学生がちょくちょくいて面白かった。ピアレビューを席で適当に座ったやつにやってもらうのは普通に苦痛なので、固定の友人を作っておくと良いと思う。

最後はグループでのポスター発表だったのだが、班員が全てやってくれて申し訳なかった。感謝を込めて一応発表は 2 回やりました（通常は 1 回）

**** GE71901 / マークアップ言語 / A
- 春 AB / 月 3 / 2 単位 / 3・4 年次
- 対面
- 専門科目 (選択)

出席を取らないので 3 回目くらいから出なくなった。XML をコネコネする授業。XPath とかは知ってるけどスタイルシートとかは知らなかったなあ。絶対今後使うことのない知識だろうけど。
レポートだけで決まるのでレポートの出し忘れには注意しましょう。俺は多分全部出したと思う。

**** GE70601 / Web プログラミング / B
- 春 AB / 木 1, 2 / 2 単位 / 3・4 年次
- 対面
- 専門科目 (選択)

出席を取らないので 3 回目くらいから出なくなった 2。1 回のレポートと最終テストだけで決まるのだが、テストが完全に過去問通り出たのでテストの回答を LLM に作らせて挑むだけで勝てる簡単な科目だった。
つっても B なんですが......

**** GE70401 / ディジタルライブラリ / A+
- 春 AB / 木 3, 4 / 2 単位 / 3・4 年次
- 対面
- 専門科目 (選択)

知識情報概論に始まり、宇陀先生あるあるの最終評価がすべての授業である。
岸辺露伴のスタンドに触れながら、全ての資料を LLM に投げることで A+ を獲得......(LLM の使用は許可されています)

**** HC36191 / 生涯発達と家族支援 / 履修中
- 春 A / 火 5, 6 / 1 単位 / 1 年次
- オンデマンド

医学群の授業には面白そうなのが多い。1〜4 回の授業を担当する女性の先生がフィラーが多すぎる！あと言い淀んで複数回言い直そうとした上で沈黙して数秒後にしっかり言い直すシーンはカットしてほしい。オンデマンドなんだから。
後半から聞いてないけど

**** HE36221 / 実践的オンラインコンテンツ・ツール活用論 / B
- 春 A / 火 5, 6 / 1 単位 / 1 年次
- オンデマンド

医学群の謎の授業だが、ちょうどいいし面白そうなので取った。結論から言うとかなり面白い授業だった。PubMed とか UCSC Genome Browser とかいう医学系のやつしか使わないであろう謎のツールを活用するのって衒学癖を刺激されて良い。
途中からプロンプトエンジニアリングみたいな授業になったのも新鮮でよかった。これが半期なのは惜しいかもだが、半期だからこそ楽しめたというところはありそう。
結構テストは点取ってた気がするんだが、相対評価なのか B だった。嘘、生成 AI を活用している人のほうが加点されてるみたいな感じだった気がする。

**** GB20602 / プログラミングチャレンジ / D
- 春 AB / 火 3, 4 / 2 単位 / 3・4 年次
- 対面 (は名ばかりでほぼオンデマンド)

競技プログラミングをやる授業なのだが、ふつうに難しすぎる。最初は骨が折れるぜ！と思いながらやっていたけど途中から重たすぎて履修中断したくなってしまった。水色コーダーくらいからまともに取り組めると思います。茶コーダーの俺にはむりぽ。
成績評価が「毎回」2 問以上解くと少なくとも C が獲得できるというものだったんだが、俺は「平均」だと思っていたので 1 回すっぽかしてしまって見事にその時点で落単が確定していた。殺して......

**** FG34711 / データ構造とアルゴリズム / B

- 春 AB / 水 3, 4 / 2 単位 / 3・4 年次
- オンデマンド (任意の日程で 1 回だけ対面がある)

グラフのアルゴリズムを主にやる授業で、アルゴリズムの説明の課題のために YouTube Shorts を利用させる一風変わった授業。1 回だけ授業に出て「存在の証明」をしないと単位が出なく、存在の証明の際には教員と 2 shot 写真を撮る！
Shorts を撮るのが重く、1 回だけ提出していない。あと文句としては実習室に俺の学生証だと入る許可が出なくて鍵が開かない。他学類が迫害されています！（別に受講はできるはず......）
GE7 にも「データ構造とアルゴリズム」という同名科目があるので、来季も同じようなことをやらないといけないと思うと気が滅入るぜ。
後半は Shorts がなくなったので食指が伸びやすかった。たぶん全部出してたら A 取れてたんだろうなあ。


** おわりに
1 科目ヘマはしたものの 21 / 23 単位は取得できていたため、秋学期で残り 12 単位取得すればよい計算です。少なくとも必修科目が 6 単位あるので、最悪は他で 6 単位（だいたい 3 科目）取れば進級はできますが、余裕を持ってキャップギリギリまで履修（編入生は初年度で 55 単位履修できる）しようと思います。俺がストレートで卒業することを願っていてください！w
