#+TITLE: 令和 3 年度（2021 年度）高専・高校 受験記
#+DESCRIPTION: 3 校受けました
#+TAGS: 受験記 高専 高校
#+DATE: 2021-03-13
#+CANONICAL: https://kyre.hatenablog.jp/entry/jyukenki
#+OPTIONS: ^:nil

[[https://twitter.com/kyure_a][Kyure_A（キュレェ）]]です。

中学校を卒業して暇になったので、駄文かつ需要のないものを書こうと思い立ちました。

俺は近所にある工業高等専門学校（以後高専）一点に絞って受験を受けたかったのですが、滑り止めとして簡単な私立を受けてしまって、後悔しています。

皆さんは私立を明確に滑り止めとして受けるのではなく、自分の実力を了知するための適正な学校を受けたほうがいいです。

そして、受験期になったら Twitter からはログアウトして、机と己に向かい合うことをおすすめします。

そうしないと自分は「努力すればもっと上の学校に行けた」と思い込んだまま一生引きずってしまうので。

以下の記事にインスパイアされています。ありがとうございました。

https://atree.hatenadiary.com/entry/jukenki

https://lisa0.hatenablog.jp/entry/2017/12/03/064218

[toc]

* 中学一年生
小学校時代の友人は中高一貫校に進学したので、中高一貫校への漠然とした憧れを持っていたものの、近所にある公立中学校に進学しました。

自分の思想に影響を与えた出来事といいますか、これが高専を選ぶ元凶となったといえる出来事といえば、本格的に Twitter を始めたことです。

当時、俺はスマホが好きな人が集まるコミュニティに所属していたのですが、そのスマホを集める人間に高専生が多かったため、影響を受けて、高専という選択肢を眼中に入れるようになりました。

https://twitter.com/Kyure_A/status/1040970344641617921

当時は仲間意識が芽生えたその一群が所属しているような学校に入ってみたい、彼らのような人間と日常的に話してみたい、というように高専に憧れを抱いていたのかもしれません（今は自分と似た人間と向き合うのは普通に嫌ですが）。

しかしながら、今思えば、憧れていたのは中高一貫である 6 年間、自由に趣味（どのようなものを想像してもらっても構いません）を自身の長所として鞠育することができる時間や空間であったのだと思います。

こうは述べていたものの勉強は一切しない日々でした。憧れとはいったものの、本当に頭の片隅に置いていただけでした。

* 中学二年生
黒歴史。この時期も Twitter をやっていましたが、一番の思春期といいますか、羞恥心という言葉があまりに矮小に聞こえるほど気持ちの悪いツイートをしていた時期だと思います。

チュウニズムというゲームに一番ハマっていたのもこの時期です。当時は体力がありました。

夏頃は高専カンファレンスに顔を出していました。中学生であると名乗れば、特殊な能力を持たない人間でも褒め称えられ持て囃される空間でした。

俺が今言いたいことであり、これから高専生になってしまう人間としてのお気持ちは、「中学生」という吹けば飛ぶような肩書きの人間を甘やかしてはならない、ということです。

#+begin_quote
「精神年齢が高い」

「この年齢でこの分野に興味があるなんてすごい」
#+end_quote

というような言葉は、その人間をつけあがらせるだけではなく、後の呪縛として襲いかかります。今、俺はこの言葉に甘やかされ、乗せられて一切の努力を怠った自分が殺したいほど憎いです。

他人の評価には惑わされずに、自己を客観視できるようになりましょう（自戒）。

https://twitter.com/Kyure_A/status/1133002909111558146
https://twitter.com/Kyure_A/status/1206183076017033218

ちなみに、10 月くらいから塾に通い始めました。しかしながらその塾は進学塾ではなくて地方の個別指導塾でした。塾の環境としては託児所みたいなかんじでしたが、勉強する場所を設けることで一日に一時間くらいは勉強できるようになりました。
（エーッ短い？）

* 中学三年生
新型コロナウイルス感染症が猛威を奮い、安倍元総理が休校を要請したのは周知の事実であろうと思います。この時期に「競技プログラミング！高校数学！」と意気込んでいたのですが、Twitter を毎日見る日々で、全くと言っていいほど勉強をしていませんでした。（前述した塾で週に二回くらい勉強するだけ）

この空白期間に一切身になることをしなかった自分の怠惰さは、一生治らないのではないかと恐怖して、そして後悔しています。この後悔は今の自分の原動力になっていますが、当時もしっかりとスキルを磨いていれば、もっと上位の学校に進学できたのではないかという未練が残り続けています。

緊急事態宣言は出されていたものの、最初のほうは休日にゲームセンターが空いていたので毎週通っていました。

https://twitter.com/Kyure_A/status/1276146259078909952

なんか進学塾ではないのに渋幕の過去問が置いてあったのはよくわかりません。

そもそも大阪の私立上位高校の過去問は置いていないのに、明らかに学力層に見合わずに距離的にも無理がある学校の過去問を置かないでほしい。

https://twitter.com/Kyure_A/status/1289908317431578624

この頃くらいに国立高専の過去問を買いました。俺の受けた高専は公立高専だったのですが、国立と同じ問題を入学試験で用いている高専であったので、のんびりやっていました。

ちなみに過去問は、国語と英語は 9 割弱を取れており、他の教科は 7 割程度という感じの点数配分でした。

この点数でも受かるだろうと浮かれていたのですが、今思うとギリギリです。

https://twitter.com/_LiSa0/status/1299270390242443264

八月くらいに高専卒のツイッタラーと会ってきました。この人、俺と会った数日後とかに京大の合格ツイートをしていたと思うので、その時は普通になんとも言えない顔になりました。

彼と話したことの内容は、高専についてや勉学についての話などで、身になる話をしていただいたと思います。これらの話を聞いてモチベーションがアップしました。ありがとうございました。

一緒にラーメン屋にも行ったのですが、普通に金を返すのを忘れていました。また会ったときに返します。申し訳無いぜ......。

* 入試総合
全体的に当日は一切緊張しませんでした。どちらかというと学校で受験当日の事を考えたときに過呼吸になる謎体質でした。

* 近畿大学工業高等専門学校
私立高専です。私立の高専があることは中学二年生くらいから知っていましたが、本当に受けるとは思いませんでした。

受けようと思ったきっかけは、模試の広告欄に掲載されていたことです。模試の広告欄で私立を選択する人は意外と多いのでは？と選んだ側としては感じています。

1/21 に受験がありました。複数の会場で受験が行われるとのことなので、俺は大阪会場（日建学院ってところ）で受験を受けたのですが、7 人くらいしか受験者がいませんでした。

例年、数学は高校範囲が出る（学力層に明らかに見合っていない）ことが自分の中で話題に上がっていましたが、今年は範囲削減の影響もあってか中学範囲にまとまっており、例年の数倍は簡単な問題であったと記憶しています。

明らかに受かる学校であったため、緊張も何もせずに休み時間にスマホをいじっていましたが、他の人はギリギリまで参考書を読んでいたので「えらいなあ」と思っていました。

英語は「I () car の括弧の中に入る単語を答えよ... 1, bye 2, buy 3, bike」みたいなガチで舐めている問題が出てきて悲しくなりながら解いてました。30 分くらい余りました。

結果は勿論といっていいのですが合格でした。しかしながら特待生制度がないので、もし本命に落ちたらクソ高い学費を払わされたりしたんだろうなあと思い、腹が立ちました。

* 大阪電気通信大学高等学校
2/10 に受験がありました。カスでした。高専に落ちた時に四年次で編入するための選択肢として工業科を選んだのですが、普通に受験料の無駄なので、適正のところ（普通科）を受けて、自分の実力を裏付ける指標を作り、自信をつけたほうがいいと思います。

特待で合格でした。学費免除とかじゃなくて振り込みで 30 万（少なくない？）が貰えるだけだったらしいです。

* 大阪府立大学工業高等専門学校（現: 大阪公立大学工業高等専門学校）
第一志望でした。

2/21 に受験がありました。友人もこの高専を一緒に受けるというのもあり、一緒に受験会場に向かいました。

前日は他の高校を受ける友人と一緒にラーメン屋に行き、8 時間くらいの過不足ない睡眠を取りました。

https://twitter.com/Kyure_A/status/1363025020646133760

この日に持っていった特有の装備品として

- チョコラ BB ハイパー
- 森永ラムネ
- お弁当

が挙げられます。

試験時間が 7 時間くらいあったので、昼食の準備をしたのと、集中力が上げられそうな小道具を持ち込みました。

プラセボ効果もあるとは思うのですが、長い睡眠時間と相まって人生で一番集中できたのではないか、と思っています。カフェイン + ブドウ糖は最強なので、皆さんもここぞというときに利用してみると嬉しくなれるでしょう。

例年に比べて数学はとても易化していました。3 完くらいできてそうだな〜と思っています。

しかしながら、例年に比べて社会はとても難化していたのでここで点数が整えられていると思いました（期待値で 40 点くらいだった気がする）。

点数の開示が 4 月上旬にあるため、開示請求をしたあかつきには成績を掲載します。

** 追記 (2022/01/11)
同じ高専の先輩方のありがたいご指導（笑）を受けて一時期この記事を非公開にしていたため、成績の掲載を忘れていました。

ほとんど高専に 1 年間ほど在籍した感想はまたいつか書くとして、取り敢えず開示された成績を掲載します。

入試得点（括弧内は傾斜配点 1.5 倍計算後）

- 国語: 96
- 数学: 67（101）
- 理科: 69（104）
- 社会: 40
- 英語: 86（129）
- Σ 358/500（470/650）

72% ほどの得点率でした。お世辞にも高いとは言えない点数であり、下で掲載している「易化していたと感じた数学」も 67 点と思いの外振るっていません。（言い訳をすると、大問 1 に例年とは違い配点が 5 点の問題が多数存在し、それを無視していたせいで点数を落としたのではないかと考えています）

全体的に文系科目で受かったと考えてもおかしくはないです。

私の受験年度は新型コロナウイルスによる休校が影響して範囲変更があったため、全体的に易化していたことと合格倍率が例年より低かったことを鑑みるとこの点数は例年では合格できない点数ではないかと考えています。

特に社会科が酷い、受験生はなんとかしたほうがいいです。（期待値で 40 点、マジだったので）

https://twitter.com/Kyure_A/status/1363340507200454658

上は休み時間にしたツイートです。本番もスマホを見たり、参考書のかわいくはないフクロウの絵を眺めていました。

受験会場での写真はお弁当しかなかったです（母上に感謝）。

そして、2/25 の合格発表では、友人共々合格していました。

https://twitter.com/Kyure_A/status/1364828426259947520

受かったときの気持ちなのですが、嬉しさと当然であろうという気持ちが 4:6 くらいでした。

友人は当時、学校を出席停止になっていたため、同じ空間で喜びを共有できなかったのは残念でしたが、両者ともに合格できて嬉しい限りでした。

* 〆の言葉
ということで、俺は *大阪府立大学工業高等専門学校* に春から入学することになりました。よろしくお願いします。

在校生や新規の入学生の方々との交流は俺の性格上、慎重に行うこととしているので、なんらかの負の感情を抱かせるアクションを行うかもしれませんが、大目に見ていただけると嬉しいです。

入学以前、そして入学してからは *数学と競技プログラミング* に本腰を入れて取り組んでいきたいと思います。また大学附属の学校であるため、図書館の蔵書も多いだろうと感じ、好奇心で心が躍っています。よかったら一緒に勉強をしていただけると嬉しい限りです。

今俺は、この学校に入ることが新たな人生のスタートになると感じています。これまでの人生で支えてくれた両親や友人、フォロワーに感謝してもしきれません。心よりありがとうございました。

そして文章を読んでくださったあなたにも感謝しています。ありがとうございました。

* 追記 (2023/08/13)
当時使っていたアカウントが凍結したため、当時のツイートが全部リンク切れになってしまいました......（本文への変更はこの追記時には行っていません）。

* 追記 (2023/09/27)
Wayback Machine に [[https://web.archive.org/web/20230331021140/https://kyre.hatenablog.jp/entry/jyukenki][アーカイブ]] があったので、どのような内容だったかのスクショを貼り付けました（このサイトではスクショを省略しています）。
