#+TITLE: おすすめ NTR・BSS 作品
#+DATE: 2026-03-10
#+DESCRIPTION: Pixiv/FANZA/DLsite ごとにイチオシを紹介する
#+TAGS: NTR
#+DRAFT: false

** はじめに
キュレェです。みなさん NTR と BSS というジャンルはご存知ですか。多分知っていると思いますが一応説明しておきます:

- NTR: 「寝取られ」の略で、彼女/妻を別の男性に（合意・不合意問わず）奪われるということです。本記事では「寝取らせ」も含むことにします。
- BSS: 「僕が先に好きだったのに」の略で、片思いしていた女性が別の男性と付き合う・セックスする、またそれを目撃する・知ってしまうみたいな感じです。

創作においては俺はこれらのジャンルが好きなので、イチオシを紹介しておきます。ここでは Pixiv/FANZA/DLsite のリンクを貼っていきます (FANZA/DLsite で両方売っている作品もあると思いますが、その場合は俺が所有しているプラットフォーム側に書きます)

** Pixiv

*** ひとづまフタコマvol.8
https://www.pixiv.net/artworks/54660085

厳密には主人公は寝取る側なので NTR というかというと怪しいが、叔父さん側に感情移入すると寝取らせなのでエロい

*** 彩度薄めな女の子のやつ
https://www.pixiv.net/artworks/87228572

この子のシリーズの中でも一番最初なのだが、以降は「他の男を知った後」かつノリノリで寝取られているのであまり趣向に合わない。堕ちる過程が描写されているこの作品が一番エロいです。

*** 文芸部の先輩
https://www.pixiv.net/artworks/95406024

自分の長いアプローチはチャラい男の数日に負けてしまうくらい価値のないものだったのかと思い知らされるのが良いです。

*** NTR BBC♠️
https://www.pixiv.net/artworks/120893298

中指ってエロいから

*** 【16P】ペニスのデカさですべてが決まる世界で粗チンの僕が奇跡的に手に入れた彼女は当然のようにデカチンに寝取られて終わる
https://terasumc.fanbox.cc/posts/7853927

マジでほぼそのままの説明になってしまうが、ありえない世界設定で奇跡的にゲットした彼女の身がデカチン様の「特権」によって奪われた上に、純粋なセックスのテクニックで心まで奪われているのがいいですね。

** FANZA
*** 蝶子-性倫理の壊れた幼馴染が見知らぬ男に抱かれる生配信を視て射精する-
https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_167476/

Twitter で見てエロすぎて探してたら全く話したことないフォロワーが見つけてくれた思い出深い作品。おすすめです。

*** 種崎かおり（39）、娘の代わりに同人AVデビュー
https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_333042/

信じろ先生の漫画は Twitter で 2 コマばかり見てシコっていたので、同人誌が出たときはとても驚いた。即オチ 2 コマがたっぷりストーリーっぽく詰まっている感じで満足度が高い。おすすめです。

*** キョウハク×ケイヤク
https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_613260/

70, 71 ページの首を絞められてマゾイキしている綺紗良 (ヒロイン) の表情が最もエロい。ここに到達するまでの前戯として他のページがあります。

** DLsite
あんまり DLsite 使ってないからアレかも

*** あすなま 6
https://www.dlsite.com/maniax/work/=/product_id/RJ241685.html

SAO のアスナがジョニー・ブラック（剣ないよぉ〜！の人）にレイプされて快楽堕ちする作品。カラーも持ってるけど俺はモノクロのほうがエロいと思う。あすなまシリーズでもアスナの表情が随一でエロい。おすすめです。

*** イジメっ子に堕とされた僕のパパ
https://www.dlsite.com/maniax/work/=/product_id/RJ01069688.html

男の娘 NTR という供給が少ないジャンルで一躍している葛千代先生の作品でどの作品も良いのだが、一番抜いたのはこれなのでピックアップした（全部書いてしまいそうになるので）

ラストのウエディングドレスを着て手コキしているシーンが特にいいです。

** おわりに
「夏のオトシゴ」は元祖 NTR と名高い作品であると思うが、俺は買ったはいいもののあっさり終わりすぎで抜けなかったので立項していない（そもそも立項するまでもない作品だしな）

寝取られる男側に感情移入して抜くので、男側が NTR・BSS されている事実を知らない作品はあまり趣向に合わない。

+男で抜いているからゲイ+
